permissions:
  contents: write  # needed to access github pages and allow it to write


name: Deploy MkDocs

on:
  push:
    branches: [master]
    paths:
      - '_Docs-Site-MkDocs_/**'
      - '.github/workflows/deploy-docs.yml'

env:
  site_path: _Docs-Site-MkDocs_

jobs:
  deploy-docs:
    name: Deploy MkDocs Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install MkDocs and Material theme
        run: pip install mkdocs mkdocs-material

      - name: Deploy Documentation
        run: mkdocs gh-deploy --config-file ${{ env.site_path }}/mkdocs.yml --force